
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elois
 */
public class Menu_De_Configuration extends javax.swing.JFrame {
private JTextField textFieldLignes;
    private JTextField textFieldColonnes;
    private JTextField textFieldBombes;
    private JButton boutonCommencer;

    /**
     * Creates new form Menu_De_Configuration
     */
    public Menu_De_Configuration(ActionListener commencerListener) {
        
        setLayout(new GridLayout(4, 2)); // GridLayout pour aligner les composants

        JLabel labelLignes = new JLabel("Nombre de lignes:");
        JLabel labelColonnes = new JLabel("Nombre de colonnes:");
        JLabel labelBombes = new JLabel("Nombre de bombes:");

        textFieldLignes = new JTextField();
        textFieldColonnes = new JTextField();
        textFieldBombes = new JTextField();

        boutonCommencer = new JButton("Commencer");
        // Ajout des composants au JPanel
        add(labelLignes);
        add(textFieldLignes);
        add(labelColonnes);
        add(textFieldColonnes);
        add(labelBombes);
        add(textFieldBombes);
        add(boutonCommencer);

        // Ajouter le ActionListener pour le bouton "Commencer"
        boutonCommencer.addActionListener(commencerListener);
    }
     // Méthode pour obtenir les valeurs de configuration
    public int getNbLignes() {
        return Integer.parseInt(textFieldLignes.getText());
    }

    public int getNbColonnes() {
        return Integer.parseInt(textFieldColonnes.getText());
    }

    public int getNbBombes() {
        return Integer.parseInt(textFieldBombes.getText());
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_De_Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_De_Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_De_Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_De_Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_De_Configuration().setVisible(true);
            }
        }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

